version: "3"

services:

  fvh_sentilonoise_in:
    build:
      context: ./platform_in/
      dockerfile: Dockerfile.prod
    #command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - config.env
    environment:
      - FLASK_APP=app/__init__.py
      - FLASK_ENV=production
      - APP_SETTINGS=app.config.ProductionConfig

  nginx:
    build: ./nginx
    ports:
      - 1339:80
    depends_on:
      - fvh_sentilonoise_in
