---
swagger: "2.0"
info:
  description: "This API accepts noise input from sensors in the sentilo format"
  version: "1.0.0"
  title: "Cesva Noise Observation API"
  contact:
    email: "sheena.puthanpurayil@forumvirium.fi"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "virtserver.swaggerhub.com"
basePath: "/FinEst-Twins/sentilonoise/1.0.0"
tags:
- name: "Observations"
schemes:
- "https"
paths:
  /cesva/v1:
    post:
      tags:
      - "Observations"
      summary: "adds noise observations to UoP"
      operationId: "cesva_v1_post"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "Sensors"
        description: "Observations from Sensors"
        required: false
        schema:
          $ref: "#/definitions/Sensors"
      responses:
        "201":
          description: "item created"
        "400":
          description: "invalid input, object invalid"
        "409":
          description: "an existing item already exists"
      x-swagger-router-controller: "swagger_server.controllers.observations_controller"
definitions:
  Sensors:
    type: "object"
    required:
    - "sensors"
    properties:
      sensors:
        type: "array"
        items:
          $ref: "#/definitions/Sensor"
    example:
      sensors:
      - observations:
        - value: "10.0"
          timestamp: "12/03/2020T12:26:58UTC"
        - value: "10.0"
          timestamp: "12/03/2020T12:26:58UTC"
        sensor: "TA120-T246174-N"
      - observations:
        - value: "10.0"
          timestamp: "12/03/2020T12:26:58UTC"
        - value: "10.0"
          timestamp: "12/03/2020T12:26:58UTC"
        sensor: "TA120-T246174-N"
  Sensor:
    required:
    - "sensor"
    properties:
      sensor:
        type: "string"
        example: "TA120-T246174-N"
      observations:
        type: "array"
        items:
          $ref: "#/definitions/Observation"
    example:
      observations:
      - value: "10.0"
        timestamp: "12/03/2020T12:26:58UTC"
      - value: "10.0"
        timestamp: "12/03/2020T12:26:58UTC"
      sensor: "TA120-T246174-N"
  Observation:
    required:
    - "timestamp"
    - "value"
    properties:
      value:
        type: "string"
        example: "10.0"
      timestamp:
        type: "string"
        format: "date-time"
        example: "12/03/2020T12:26:58UTC"
    example:
      value: "10.0"
      timestamp: "12/03/2020T12:26:58UTC"
